### PR TITLE
[dev] - Bug AB#69096: [Giving][Android/Logged In/Out]- The "New Gift" and the "Thank you Confirmation" Pages are not opening completely! there is a Gap on the top of the pages

### PR DESCRIPTION
**Pull request by pakkibokati2012**

### CODE REVIEW

**Comment by pakkibokati2012** [comment]
@War777, @raoufr, I need your help testing this pr in notch and non-notched android devices.

**Comment by raoufr** [comment]
@bittu1028 do you mind if you help @pakkibokati2012 test this PR with the ME app? thanks very much

**Review by bittu1028 — APPROVED** [review]

**Comment by bittu1028** [comment]
@raoufr  i tested on my device and its working properly

**Review by raoufr — APPROVED** [review]

**Comment by raoufr** [comment]
thank you very much @bittu1028

**Pull request merged**
