### PR TITLE
[dev] - NO PBI- Fixed picker icon on SelectPIcker on Android and added font family to text Input

### PR DESCRIPTION
**Pull request by bittu1028**

### CODE REVIEW

**Review by raoufr — APPROVED** [review]
@bittu1028 please add a change log entry for this fix and we should be good to merge and release. Thank you.

**Comment by krishnakant-technossus** [comment]
@bittu1028 @ajaybushel, still this fix not resolves the issue which I was facing in android device. I tested this here, please check attached image for the same.

Screenshot_20220729-180752_Mau

I can still see that native icon beside custom icon. can you please check?

**Comment by bittu1028** [comment]
@krishnakant-technossus  its working for me
296023157_530118652202811_4518636813612049643_n

Please check your branch name if its matches this PR

**Comment by krishnakant-technossus** [comment]
> @krishnakant-technossus its working for me 296023157_530118652202811_4518636813612049643_n
> 
> Please check your branch name if its matches this PR

Yes I have checked with this branch only. but I have passed showCustomIcon prop. in this case, you will be able to see both carets.

**Comment by bittu1028** [comment]
> > @krishnakant-technossus its working for me 296023157_530118652202811_4518636813612049643_n
> > Please check your branch name if its matches this PR
> 
> Yes I have checked with this branch only. but I have passed showCustomIcon prop. in this case, you will be able to see both carets.

Dont pass showCustomIcon prop its for darkMode and Me app. You will see 1 icon as default for your app

**Pull request merged**
